server:
  port: 7526
  max-http-header-size: 4048576

springbootdo:
  imagePath: file:///G:/ideaproject/youwenbida/youwenbida-consumer/src/main/resources/image/

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: Consumer
      check: false
      timeout: 600000
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://127.0.0.1:2181
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20110
    scan: cn.psw.youwenbida.consumer.controller #扫描的包名
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
  jackson:
      time-zone: Asia/Shanghai


logging:
  config: classpath:logback-boot.xml

