server:
  port: 7526
  max-http-header-size: 4048576

spring:
  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: Provide
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://127.0.0.1:2181
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20110
    scan: cn.psw.youwenbida.consumer.controller #扫描的包名
    consumer:
      check: false
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
  jackson:
      time-zone: Asia/Shanghai


logging:
  config: classpath:logback-boot.xml

